<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="appledeMacBook-Pro.local" name="com.panyu.mytestng.OtherTest" tests="3" failures="0" timestamp="23 Nov 2020 09:13:41 GMT" time="3.017" errors="1">
  <testcase name="testCase2" time="3.017" classname="com.panyu.mytestng.OtherTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.panyu.mytestng.OtherTest.testCase2() didn&#039;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.panyu.mytestng.OtherTest.testCase2() didn't finish within the time-out 3000
at java.util.concurrent.ThreadPoolExecutor.tryTerminate(ThreadPoolExecutor.java:713)
at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1014)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- testCase2 -->
  <testcase name="testCase3" time="0.000" classname="com.panyu.mytestng.OtherTest"/>
  <testcase name="testCase1" classname="com.panyu.mytestng.OtherTest">
    <skipped/>
  </testcase> <!-- testCase1 -->
</testsuite> <!-- com.panyu.mytestng.OtherTest -->
